package seeder

import "github.com/agambondan/eduplay/services/api/internal/model"

// generatedCountries returns the Phase 7 flag quiz country dataset.
// Source metadata: REST Countries v3.1 all endpoint.
// Source SVG flags: country-flag-icons 3x2 assets with selected flag-icons detail overrides.
// Regenerate with: node scripts/sync-country-flags.mjs
func generatedCountries() []model.Country {
	return []model.Country{
		{Name: "Afganistan", Capital: "Kabul", FlagEmoji: "🇦🇫", FlagCode: "AF", Region: "asia"},
		{Name: "Afrika Selatan", Capital: "Pretoria", FlagEmoji: "🇿🇦", FlagCode: "ZA", Region: "africa"},
		{Name: "Afrika Tengah", Capital: "Bangui", FlagEmoji: "🇨🇫", FlagCode: "CF", Region: "africa"},
		{Name: "Albania", Capital: "Tirana", FlagEmoji: "🇦🇱", FlagCode: "AL", Region: "europe"},
		{Name: "Aljazair", Capital: "Algiers", FlagEmoji: "🇩🇿", FlagCode: "DZ", Region: "africa"},
		{Name: "Amerika Serikat", Capital: "Washington, D.C.", FlagEmoji: "🇺🇸", FlagCode: "US", Region: "americas"},
		{Name: "Andora", Capital: "Andorra la Vella", FlagEmoji: "🇦🇩", FlagCode: "AD", Region: "europe"},
		{Name: "Angola", Capital: "Luanda", FlagEmoji: "🇦🇴", FlagCode: "AO", Region: "africa"},
		{Name: "Antigua dan Barbuda", Capital: "Saint John's", FlagEmoji: "🇦🇬", FlagCode: "AG", Region: "americas"},
		{Name: "Arab Saudi", Capital: "Riyadh", FlagEmoji: "🇸🇦", FlagCode: "SA", Region: "asia"},
		{Name: "Argentina", Capital: "Buenos Aires", FlagEmoji: "🇦🇷", FlagCode: "AR", Region: "americas"},
		{Name: "Armenia", Capital: "Yerevan", FlagEmoji: "🇦🇲", FlagCode: "AM", Region: "asia"},
		{Name: "Australia", Capital: "Canberra", FlagEmoji: "🇦🇺", FlagCode: "AU", Region: "oceania"},
		{Name: "Austria", Capital: "Vienna", FlagEmoji: "🇦🇹", FlagCode: "AT", Region: "europe"},
		{Name: "Azerbaijan", Capital: "Baku", FlagEmoji: "🇦🇿", FlagCode: "AZ", Region: "asia"},
		{Name: "Bahama", Capital: "Nassau", FlagEmoji: "🇧🇸", FlagCode: "BS", Region: "americas"},
		{Name: "Bahrain", Capital: "Manama", FlagEmoji: "🇧🇭", FlagCode: "BH", Region: "asia"},
		{Name: "Banglades", Capital: "Dhaka", FlagEmoji: "🇧🇩", FlagCode: "BD", Region: "asia"},
		{Name: "Barbados", Capital: "Bridgetown", FlagEmoji: "🇧🇧", FlagCode: "BB", Region: "americas"},
		{Name: "Belanda", Capital: "Amsterdam", FlagEmoji: "🇳🇱", FlagCode: "NL", Region: "europe"},
		{Name: "Belarus", Capital: "Minsk", FlagEmoji: "🇧🇾", FlagCode: "BY", Region: "europe"},
		{Name: "Belgia", Capital: "Brussels", FlagEmoji: "🇧🇪", FlagCode: "BE", Region: "europe"},
		{Name: "Beliza", Capital: "Belmopan", FlagEmoji: "🇧🇿", FlagCode: "BZ", Region: "americas"},
		{Name: "Benin", Capital: "Porto-Novo", FlagEmoji: "🇧🇯", FlagCode: "BJ", Region: "africa"},
		{Name: "Bolivia", Capital: "Sucre", FlagEmoji: "🇧🇴", FlagCode: "BO", Region: "americas"},
		{Name: "Bosnia dan Herzegovina", Capital: "Sarajevo", FlagEmoji: "🇧🇦", FlagCode: "BA", Region: "europe"},
		{Name: "Botswana", Capital: "Gaborone", FlagEmoji: "🇧🇼", FlagCode: "BW", Region: "africa"},
		{Name: "Brasil", Capital: "Brasília", FlagEmoji: "🇧🇷", FlagCode: "BR", Region: "americas"},
		{Name: "Brunei Darusalam", Capital: "Bandar Seri Begawan", FlagEmoji: "🇧🇳", FlagCode: "BN", Region: "asia"},
		{Name: "Bulgaria", Capital: "Sofia", FlagEmoji: "🇧🇬", FlagCode: "BG", Region: "europe"},
		{Name: "Burkina Faso", Capital: "Ouagadougou", FlagEmoji: "🇧🇫", FlagCode: "BF", Region: "africa"},
		{Name: "Burundi", Capital: "Gitega", FlagEmoji: "🇧🇮", FlagCode: "BI", Region: "africa"},
		{Name: "Butan", Capital: "Thimphu", FlagEmoji: "🇧🇹", FlagCode: "BT", Region: "asia"},
		{Name: "Cad", Capital: "N'Djamena", FlagEmoji: "🇹🇩", FlagCode: "TD", Region: "africa"},
		{Name: "Ceko", Capital: "Prague", FlagEmoji: "🇨🇿", FlagCode: "CZ", Region: "europe"},
		{Name: "Cili", Capital: "Santiago", FlagEmoji: "🇨🇱", FlagCode: "CL", Region: "americas"},
		{Name: "Denmark", Capital: "Copenhagen", FlagEmoji: "🇩🇰", FlagCode: "DK", Region: "europe"},
		{Name: "Dominika", Capital: "Roseau", FlagEmoji: "🇩🇲", FlagCode: "DM", Region: "americas"},
		{Name: "Ekuador", Capital: "Quito", FlagEmoji: "🇪🇨", FlagCode: "EC", Region: "americas"},
		{Name: "El Salvador", Capital: "San Salvador", FlagEmoji: "🇸🇻", FlagCode: "SV", Region: "americas"},
		{Name: "Emirat Arab", Capital: "Abu Dhabi", FlagEmoji: "🇦🇪", FlagCode: "AE", Region: "asia"},
		{Name: "Eritrea", Capital: "Asmara", FlagEmoji: "🇪🇷", FlagCode: "ER", Region: "africa"},
		{Name: "Estonia", Capital: "Tallinn", FlagEmoji: "🇪🇪", FlagCode: "EE", Region: "europe"},
		{Name: "Eswatini", Capital: "Mbabane", FlagEmoji: "🇸🇿", FlagCode: "SZ", Region: "africa"},
		{Name: "Etiopia", Capital: "Addis Ababa", FlagEmoji: "🇪🇹", FlagCode: "ET", Region: "africa"},
		{Name: "Fiji", Capital: "Suva", FlagEmoji: "🇫🇯", FlagCode: "FJ", Region: "oceania"},
		{Name: "Filipina", Capital: "Manila", FlagEmoji: "🇵🇭", FlagCode: "PH", Region: "asia"},
		{Name: "Finlandia", Capital: "Helsinki", FlagEmoji: "🇫🇮", FlagCode: "FI", Region: "europe"},
		{Name: "Gabon", Capital: "Libreville", FlagEmoji: "🇬🇦", FlagCode: "GA", Region: "africa"},
		{Name: "Gambia", Capital: "Banjul", FlagEmoji: "🇬🇲", FlagCode: "GM", Region: "africa"},
		{Name: "Gana", Capital: "Accra", FlagEmoji: "🇬🇭", FlagCode: "GH", Region: "africa"},
		{Name: "Georgia", Capital: "Tbilisi", FlagEmoji: "🇬🇪", FlagCode: "GE", Region: "asia"},
		{Name: "Ginea", Capital: "Conakry", FlagEmoji: "🇬🇳", FlagCode: "GN", Region: "africa"},
		{Name: "Ginea dan Bisau", Capital: "Bissau", FlagEmoji: "🇬🇼", FlagCode: "GW", Region: "africa"},
		{Name: "Ginea Ekuator", Capital: "Ciudad de la Paz", FlagEmoji: "🇬🇶", FlagCode: "GQ", Region: "africa"},
		{Name: "Grenada", Capital: "St. George's", FlagEmoji: "🇬🇩", FlagCode: "GD", Region: "americas"},
		{Name: "Guatemala", Capital: "Guatemala City", FlagEmoji: "🇬🇹", FlagCode: "GT", Region: "americas"},
		{Name: "Guyana", Capital: "Georgetown", FlagEmoji: "🇬🇾", FlagCode: "GY", Region: "americas"},
		{Name: "Haiti", Capital: "Port-au-Prince", FlagEmoji: "🇭🇹", FlagCode: "HT", Region: "americas"},
		{Name: "Honduras", Capital: "Tegucigalpa", FlagEmoji: "🇭🇳", FlagCode: "HN", Region: "americas"},
		{Name: "Hungaria", Capital: "Budapest", FlagEmoji: "🇭🇺", FlagCode: "HU", Region: "europe"},
		{Name: "India", Capital: "New Delhi", FlagEmoji: "🇮🇳", FlagCode: "IN", Region: "asia"},
		{Name: "Indonesia", Capital: "Jakarta", FlagEmoji: "🇮🇩", FlagCode: "ID", Region: "asia"},
		{Name: "Inggris", Capital: "London", FlagEmoji: "🇬🇧", FlagCode: "GB", Region: "europe"},
		{Name: "Irak", Capital: "Baghdad", FlagEmoji: "🇮🇶", FlagCode: "IQ", Region: "asia"},
		{Name: "Iran", Capital: "Tehran", FlagEmoji: "🇮🇷", FlagCode: "IR", Region: "asia"},
		{Name: "Irlandia", Capital: "Dublin", FlagEmoji: "🇮🇪", FlagCode: "IE", Region: "europe"},
		{Name: "Islandia", Capital: "Reykjavik", FlagEmoji: "🇮🇸", FlagCode: "IS", Region: "europe"},
		{Name: "Israel", Capital: "Jerusalem", FlagEmoji: "🇮🇱", FlagCode: "IL", Region: "asia"},
		{Name: "Italia", Capital: "Rome", FlagEmoji: "🇮🇹", FlagCode: "IT", Region: "europe"},
		{Name: "Jamaika", Capital: "Kingston", FlagEmoji: "🇯🇲", FlagCode: "JM", Region: "americas"},
		{Name: "Jepang", Capital: "Tokyo", FlagEmoji: "🇯🇵", FlagCode: "JP", Region: "asia"},
		{Name: "Jerman", Capital: "Berlin", FlagEmoji: "🇩🇪", FlagCode: "DE", Region: "europe"},
		{Name: "Jibuti", Capital: "Djibouti", FlagEmoji: "🇩🇯", FlagCode: "DJ", Region: "africa"},
		{Name: "Kamboja", Capital: "Phnom Penh", FlagEmoji: "🇰🇭", FlagCode: "KH", Region: "asia"},
		{Name: "Kamerun", Capital: "Yaoundé", FlagEmoji: "🇨🇲", FlagCode: "CM", Region: "africa"},
		{Name: "Kanada", Capital: "Ottawa", FlagEmoji: "🇨🇦", FlagCode: "CA", Region: "americas"},
		{Name: "Kazakstan", Capital: "Astana", FlagEmoji: "🇰🇿", FlagCode: "KZ", Region: "asia"},
		{Name: "Kenya", Capital: "Nairobi", FlagEmoji: "🇰🇪", FlagCode: "KE", Region: "africa"},
		{Name: "Kepulauan Marsal", Capital: "Majuro", FlagEmoji: "🇲🇭", FlagCode: "MH", Region: "oceania"},
		{Name: "Kepulauan Solomon", Capital: "Honiara", FlagEmoji: "🇸🇧", FlagCode: "SB", Region: "oceania"},
		{Name: "Kirgistan", Capital: "Bishkek", FlagEmoji: "🇰🇬", FlagCode: "KG", Region: "asia"},
		{Name: "Kiribati", Capital: "South Tarawa", FlagEmoji: "🇰🇮", FlagCode: "KI", Region: "oceania"},
		{Name: "Kolombia", Capital: "Bogotá", FlagEmoji: "🇨🇴", FlagCode: "CO", Region: "americas"},
		{Name: "Komoro", Capital: "Moroni", FlagEmoji: "🇰🇲", FlagCode: "KM", Region: "africa"},
		{Name: "Kongo", Capital: "Brazzaville", FlagEmoji: "🇨🇬", FlagCode: "CG", Region: "africa"},
		{Name: "Korea Selatan", Capital: "Seoul", FlagEmoji: "🇰🇷", FlagCode: "KR", Region: "asia"},
		{Name: "Korea Utara", Capital: "Pyongyang", FlagEmoji: "🇰🇵", FlagCode: "KP", Region: "asia"},
		{Name: "Kosta Rika", Capital: "San José", FlagEmoji: "🇨🇷", FlagCode: "CR", Region: "americas"},
		{Name: "Kroasia", Capital: "Zagreb", FlagEmoji: "🇭🇷", FlagCode: "HR", Region: "europe"},
		{Name: "Kuba", Capital: "Havana", FlagEmoji: "🇨🇺", FlagCode: "CU", Region: "americas"},
		{Name: "Kuwait", Capital: "Kuwait City", FlagEmoji: "🇰🇼", FlagCode: "KW", Region: "asia"},
		{Name: "Laos", Capital: "Vientiane", FlagEmoji: "🇱🇦", FlagCode: "LA", Region: "asia"},
		{Name: "Latvia", Capital: "Riga", FlagEmoji: "🇱🇻", FlagCode: "LV", Region: "europe"},
		{Name: "Lesoto", Capital: "Maseru", FlagEmoji: "🇱🇸", FlagCode: "LS", Region: "africa"},
		{Name: "Libanon", Capital: "Beirut", FlagEmoji: "🇱🇧", FlagCode: "LB", Region: "asia"},
		{Name: "Liberia", Capital: "Monrovia", FlagEmoji: "🇱🇷", FlagCode: "LR", Region: "africa"},
		{Name: "Libya", Capital: "Tripoli", FlagEmoji: "🇱🇾", FlagCode: "LY", Region: "africa"},
		{Name: "Liktenstin", Capital: "Vaduz", FlagEmoji: "🇱🇮", FlagCode: "LI", Region: "europe"},
		{Name: "Lituania", Capital: "Vilnius", FlagEmoji: "🇱🇹", FlagCode: "LT", Region: "europe"},
		{Name: "Luksemburg", Capital: "Luxembourg", FlagEmoji: "🇱🇺", FlagCode: "LU", Region: "europe"},
		{Name: "Madagaskar", Capital: "Antananarivo", FlagEmoji: "🇲🇬", FlagCode: "MG", Region: "africa"},
		{Name: "Maladewa", Capital: "Malé", FlagEmoji: "🇲🇻", FlagCode: "MV", Region: "asia"},
		{Name: "Malawi", Capital: "Lilongwe", FlagEmoji: "🇲🇼", FlagCode: "MW", Region: "africa"},
		{Name: "Malaysia", Capital: "Kuala Lumpur", FlagEmoji: "🇲🇾", FlagCode: "MY", Region: "asia"},
		{Name: "Mali", Capital: "Bamako", FlagEmoji: "🇲🇱", FlagCode: "ML", Region: "africa"},
		{Name: "Malta", Capital: "Valletta", FlagEmoji: "🇲🇹", FlagCode: "MT", Region: "europe"},
		{Name: "Maroko", Capital: "Rabat", FlagEmoji: "🇲🇦", FlagCode: "MA", Region: "africa"},
		{Name: "Masedonia Utara", Capital: "Skopje", FlagEmoji: "🇲🇰", FlagCode: "MK", Region: "europe"},
		{Name: "Mauritania", Capital: "Nouakchott", FlagEmoji: "🇲🇷", FlagCode: "MR", Region: "africa"},
		{Name: "Mauritius", Capital: "Port Louis", FlagEmoji: "🇲🇺", FlagCode: "MU", Region: "africa"},
		{Name: "Meksiko", Capital: "Mexico City", FlagEmoji: "🇲🇽", FlagCode: "MX", Region: "americas"},
		{Name: "Mesir", Capital: "Cairo", FlagEmoji: "🇪🇬", FlagCode: "EG", Region: "africa"},
		{Name: "Mikronesia", Capital: "Palikir", FlagEmoji: "🇫🇲", FlagCode: "FM", Region: "oceania"},
		{Name: "Moldova", Capital: "Chișinău", FlagEmoji: "🇲🇩", FlagCode: "MD", Region: "europe"},
		{Name: "Monako", Capital: "Monaco", FlagEmoji: "🇲🇨", FlagCode: "MC", Region: "europe"},
		{Name: "Mongolia", Capital: "Ulan Bator", FlagEmoji: "🇲🇳", FlagCode: "MN", Region: "asia"},
		{Name: "Montenegro", Capital: "Podgorica", FlagEmoji: "🇲🇪", FlagCode: "ME", Region: "europe"},
		{Name: "Mozambik", Capital: "Maputo", FlagEmoji: "🇲🇿", FlagCode: "MZ", Region: "africa"},
		{Name: "Myanmar", Capital: "Naypyidaw", FlagEmoji: "🇲🇲", FlagCode: "MM", Region: "asia"},
		{Name: "Namibia", Capital: "Windhoek", FlagEmoji: "🇳🇦", FlagCode: "NA", Region: "africa"},
		{Name: "Nauru", Capital: "Yaren", FlagEmoji: "🇳🇷", FlagCode: "NR", Region: "oceania"},
		{Name: "Nepal", Capital: "Kathmandu", FlagEmoji: "🇳🇵", FlagCode: "NP", Region: "asia"},
		{Name: "Niger", Capital: "Niamey", FlagEmoji: "🇳🇪", FlagCode: "NE", Region: "africa"},
		{Name: "Nigeria", Capital: "Abuja", FlagEmoji: "🇳🇬", FlagCode: "NG", Region: "africa"},
		{Name: "Nikaragua", Capital: "Managua", FlagEmoji: "🇳🇮", FlagCode: "NI", Region: "americas"},
		{Name: "Norwegia", Capital: "Oslo", FlagEmoji: "🇳🇴", FlagCode: "NO", Region: "europe"},
		{Name: "Oman", Capital: "Muscat", FlagEmoji: "🇴🇲", FlagCode: "OM", Region: "asia"},
		{Name: "Pakistan", Capital: "Islamabad", FlagEmoji: "🇵🇰", FlagCode: "PK", Region: "asia"},
		{Name: "Palau", Capital: "Ngerulmud", FlagEmoji: "🇵🇼", FlagCode: "PW", Region: "oceania"},
		{Name: "Palestina", Capital: "Ramallah", FlagEmoji: "🇵🇸", FlagCode: "PS", Region: "asia"},
		{Name: "Panama", Capital: "Panama City", FlagEmoji: "🇵🇦", FlagCode: "PA", Region: "americas"},
		{Name: "Pantai Gading", Capital: "Yamoussoukro", FlagEmoji: "🇨🇮", FlagCode: "CI", Region: "africa"},
		{Name: "Papua Nugini", Capital: "Port Moresby", FlagEmoji: "🇵🇬", FlagCode: "PG", Region: "oceania"},
		{Name: "Paraguai", Capital: "Asunción", FlagEmoji: "🇵🇾", FlagCode: "PY", Region: "americas"},
		{Name: "Peru", Capital: "Lima", FlagEmoji: "🇵🇪", FlagCode: "PE", Region: "americas"},
		{Name: "Polandia", Capital: "Warsaw", FlagEmoji: "🇵🇱", FlagCode: "PL", Region: "europe"},
		{Name: "Portugal", Capital: "Lisbon", FlagEmoji: "🇵🇹", FlagCode: "PT", Region: "europe"},
		{Name: "Prancis", Capital: "Paris", FlagEmoji: "🇫🇷", FlagCode: "FR", Region: "europe"},
		{Name: "Qatar", Capital: "Doha", FlagEmoji: "🇶🇦", FlagCode: "QA", Region: "asia"},
		{Name: "Republik Demokratik Kongo", Capital: "Kinshasa", FlagEmoji: "🇨🇩", FlagCode: "CD", Region: "africa"},
		{Name: "Republik Dominika", Capital: "Santo Domingo", FlagEmoji: "🇩🇴", FlagCode: "DO", Region: "americas"},
		{Name: "Rumania", Capital: "Bucharest", FlagEmoji: "🇷🇴", FlagCode: "RO", Region: "europe"},
		{Name: "Rusia", Capital: "Moscow", FlagEmoji: "🇷🇺", FlagCode: "RU", Region: "europe"},
		{Name: "Ruwanda", Capital: "Kigali", FlagEmoji: "🇷🇼", FlagCode: "RW", Region: "africa"},
		{Name: "Samoa", Capital: "Apia", FlagEmoji: "🇼🇸", FlagCode: "WS", Region: "oceania"},
		{Name: "San Marino", Capital: "City of San Marino", FlagEmoji: "🇸🇲", FlagCode: "SM", Region: "europe"},
		{Name: "Santa Lusia", Capital: "Castries", FlagEmoji: "🇱🇨", FlagCode: "LC", Region: "americas"},
		{Name: "Santo Kits dan Nevis", Capital: "Basseterre", FlagEmoji: "🇰🇳", FlagCode: "KN", Region: "americas"},
		{Name: "Santo Tomas dan Prinsipe", Capital: "São Tomé", FlagEmoji: "🇸🇹", FlagCode: "ST", Region: "africa"},
		{Name: "Santo Vinsen dan Grenadin", Capital: "Kingstown", FlagEmoji: "🇻🇨", FlagCode: "VC", Region: "americas"},
		{Name: "Seisel", Capital: "Victoria", FlagEmoji: "🇸🇨", FlagCode: "SC", Region: "africa"},
		{Name: "Selandia Baru", Capital: "Wellington", FlagEmoji: "🇳🇿", FlagCode: "NZ", Region: "oceania"},
		{Name: "Senegal", Capital: "Dakar", FlagEmoji: "🇸🇳", FlagCode: "SN", Region: "africa"},
		{Name: "Serbia", Capital: "Belgrade", FlagEmoji: "🇷🇸", FlagCode: "RS", Region: "europe"},
		{Name: "Siera Leoni", Capital: "Freetown", FlagEmoji: "🇸🇱", FlagCode: "SL", Region: "africa"},
		{Name: "Singapura", Capital: "Singapore", FlagEmoji: "🇸🇬", FlagCode: "SG", Region: "asia"},
		{Name: "Siprus", Capital: "Nicosia", FlagEmoji: "🇨🇾", FlagCode: "CY", Region: "asia"},
		{Name: "Slowakia", Capital: "Bratislava", FlagEmoji: "🇸🇰", FlagCode: "SK", Region: "europe"},
		{Name: "Slowenia", Capital: "Ljubljana", FlagEmoji: "🇸🇮", FlagCode: "SI", Region: "europe"},
		{Name: "Somalia", Capital: "Mogadishu", FlagEmoji: "🇸🇴", FlagCode: "SO", Region: "africa"},
		{Name: "Spanyol", Capital: "Madrid", FlagEmoji: "🇪🇸", FlagCode: "ES", Region: "europe"},
		{Name: "Sri Lanka", Capital: "Sri Jayawardenepura Kotte", FlagEmoji: "🇱🇰", FlagCode: "LK", Region: "asia"},
		{Name: "Sudan", Capital: "Khartoum", FlagEmoji: "🇸🇩", FlagCode: "SD", Region: "africa"},
		{Name: "Sudan Selatan", Capital: "Juba", FlagEmoji: "🇸🇸", FlagCode: "SS", Region: "africa"},
		{Name: "Suriah", Capital: "Damascus", FlagEmoji: "🇸🇾", FlagCode: "SY", Region: "asia"},
		{Name: "Suriname", Capital: "Paramaribo", FlagEmoji: "🇸🇷", FlagCode: "SR", Region: "americas"},
		{Name: "Swedia", Capital: "Stockholm", FlagEmoji: "🇸🇪", FlagCode: "SE", Region: "europe"},
		{Name: "Swis", Capital: "Bern", FlagEmoji: "🇨🇭", FlagCode: "CH", Region: "europe"},
		{Name: "Tailan", Capital: "Bangkok", FlagEmoji: "🇹🇭", FlagCode: "TH", Region: "asia"},
		{Name: "Tajikistan", Capital: "Dushanbe", FlagEmoji: "🇹🇯", FlagCode: "TJ", Region: "asia"},
		{Name: "Tanjung Hijau", Capital: "Praia", FlagEmoji: "🇨🇻", FlagCode: "CV", Region: "africa"},
		{Name: "Tanzania", Capital: "Dodoma", FlagEmoji: "🇹🇿", FlagCode: "TZ", Region: "africa"},
		{Name: "Timor Leste", Capital: "Dili", FlagEmoji: "🇹🇱", FlagCode: "TL", Region: "asia"},
		{Name: "Tiongkok", Capital: "Beijing", FlagEmoji: "🇨🇳", FlagCode: "CN", Region: "asia"},
		{Name: "Togo", Capital: "Lomé", FlagEmoji: "🇹🇬", FlagCode: "TG", Region: "africa"},
		{Name: "Tonga", Capital: "Nuku'alofa", FlagEmoji: "🇹🇴", FlagCode: "TO", Region: "oceania"},
		{Name: "Trinidad dan Tobago", Capital: "Port of Spain", FlagEmoji: "🇹🇹", FlagCode: "TT", Region: "americas"},
		{Name: "Tunisia", Capital: "Tunis", FlagEmoji: "🇹🇳", FlagCode: "TN", Region: "africa"},
		{Name: "Turki", Capital: "Ankara", FlagEmoji: "🇹🇷", FlagCode: "TR", Region: "asia"},
		{Name: "Turmenistan", Capital: "Ashgabat", FlagEmoji: "🇹🇲", FlagCode: "TM", Region: "asia"},
		{Name: "Tuvalu", Capital: "Funafuti", FlagEmoji: "🇹🇻", FlagCode: "TV", Region: "oceania"},
		{Name: "Uganda", Capital: "Kampala", FlagEmoji: "🇺🇬", FlagCode: "UG", Region: "africa"},
		{Name: "Ukraina", Capital: "Kyiv", FlagEmoji: "🇺🇦", FlagCode: "UA", Region: "europe"},
		{Name: "Uruguai", Capital: "Montevideo", FlagEmoji: "🇺🇾", FlagCode: "UY", Region: "americas"},
		{Name: "Uzbekistan", Capital: "Tashkent", FlagEmoji: "🇺🇿", FlagCode: "UZ", Region: "asia"},
		{Name: "Vanuatu", Capital: "Port Vila", FlagEmoji: "🇻🇺", FlagCode: "VU", Region: "oceania"},
		{Name: "Vatikan", Capital: "Vatican City", FlagEmoji: "🇻🇦", FlagCode: "VA", Region: "europe"},
		{Name: "Venezuela", Capital: "Caracas", FlagEmoji: "🇻🇪", FlagCode: "VE", Region: "americas"},
		{Name: "Vietnam", Capital: "Hanoi", FlagEmoji: "🇻🇳", FlagCode: "VN", Region: "asia"},
		{Name: "Yaman", Capital: "Sana'a", FlagEmoji: "🇾🇪", FlagCode: "YE", Region: "asia"},
		{Name: "Yordania", Capital: "Amman", FlagEmoji: "🇯🇴", FlagCode: "JO", Region: "asia"},
		{Name: "Yunani", Capital: "Athens", FlagEmoji: "🇬🇷", FlagCode: "GR", Region: "europe"},
		{Name: "Zambia", Capital: "Lusaka", FlagEmoji: "🇿🇲", FlagCode: "ZM", Region: "africa"},
		{Name: "Zimbabwe", Capital: "Harare", FlagEmoji: "🇿🇼", FlagCode: "ZW", Region: "africa"},
	}
}
